Allow multiple template_values files & use in favorites
cargo-generate/cargo-generate pull request #296
Opened 2021-02-16 12:56 UTC by taurr

Allows to specify --template-values-file multiple times, each file being merged in order.

Allows the favorite feature to specify a template-value-file, that is used for getting "default" values.

2021-02-16 18:20 UTC, sassman commented
could you please add at least a test and some documentation on the `README.md` to illustrate how this might be useful?

2021-02-16 19:29 UTC, taurr commented
I will add a test and expand on the README.

Actually, this should probably be a draft PR for now - as it seems you may be interested in the folder stuff, I think I need to ponder a little more on this feature... got some nice goodies and usecases for what it enables, though I don't actually think I need to allow multiple option on the command line for it (just ocurred to me!)

2021-02-16 19:44 UTC, sassman commented
Sure I will give it some thoughts. Meanwhile please mark the pr as draft. So it can't be merged.

2021-02-19 08:56 UTC, sassman requested changes
In general I find the idea appealing, so I'm very glad if you could finish the missing pieces that have been addressed.

2021-02-19 08:56 UTC, sassman commented on src/lib.rs
> +        .iter()
the `create_git` function has grew a lot, could you please refactor this part that does now the template value collection into an own function something like `collect_template_values_from_files` to reduce the responsibilities of this function. 

You could then also add a very small unit test for the function.

2021-02-25 09:27 UTC, sassman commented
@taurr this needs a rebase

2021-02-25 21:41 UTC, taurr commented
yeah, I know - kinda more focused on #295 right now and TBH. I don't want to redo everything once that hopefully lands.

This feature may end up being easier for me to just re-implement once we complete #295 - there's a reason for this one being draft for now :-)

That'll teach me not to attempt multiple features at the same time! (or, one could hope, but it's most likely not going to change anything)

2021-07-25 19:48 UTC, taurr commented
Rebased, but failing SSH tests in workflow

2021-07-30 14:31 UTC, taurr commented
Closed as this needs reimplementation anyway.

Issue #389 created to discuss/agree upon the scope.

2021-07-30 14:31 UTC, closed without merging