Override project_dir when using `generate()`
cargo-generate/cargo-generate pull request #625
Opened 2022-06-06 00:10 UTC by yozhgoor

Hello there!

I made this PR to add the `dest` argument to the `generate` function.

This argument override the destination of the project if we give a path to the `generate` function.
If we give `None`, the behaviour stay the same as expected.

2022-06-06 13:09 UTC, sassman requested changes
Nice idea, I think the breaking change is not a biggie, we can roll it with a new major version then.

2022-06-06 13:09 UTC, sassman commented on src/lib.rs
> +    if let Some(path) = dest {
I suggest avoiding the big if / else branches by leveraging default unwrapping. 
Please have a look at da42a32aead7b55828fb0bf95b154474e800be25 where I refined the function a little to be more functional style and also more DRY than it was before.

2022-06-06 13:16 UTC, sassman commented
But one more note on the idea; I think this is worth to introduce as a CLI parameter, where folks can pass a different `--base-path` than `$CWD`, so if that parameter is omitted it is set to CWD. 
By doing so users can provide it via CLI params, and it would be encapsulated in `Args` so the function signature also would not have to change.

2022-06-07 19:41 UTC, yozhgoor commented
I replaced the `dest` argument from `generate()` by a `--destination` parameter. 
It conflict with `--init` so you can choose between a subfolder, the current directory or a given path.

2022-06-07 21:57 UTC, sassman approved these changes
Nice!

2022-06-07 21:58 UTC, sassman requested changes
could you please also add one more test for the new argument?

2022-06-08 20:41 UTC, merged